
/* This file is generated by Preloader Generator */

#include "pinmux_config.h"

/* For shared IO 48 */
unsigned long sys_mgr_init_table_shared[CONFIG_HPS_PINMUX_NUM_SHARED] = {
	0xF,	/* SHARED_Q1_1 */
	0xF,	/* SHARED_Q1_2 */
	0xF,	/* SHARED_Q1_3 */
	0xF,	/* SHARED_Q1_4 */
	0xF,	/* SHARED_Q1_5 */
	0xF,	/* SHARED_Q1_6 */
	0xF,	/* SHARED_Q1_7 */
	0xF,	/* SHARED_Q1_8 */
	0xF,	/* SHARED_Q1_9 */
	0xF,	/* SHARED_Q1_10 */
	0xF,	/* SHARED_Q1_11 */
	0xF,	/* SHARED_Q1_12 */
	0xF,	/* SHARED_Q2_1 */
	0xF,	/* SHARED_Q2_2 */
	0xF,	/* SHARED_Q2_3 */
	0xF,	/* SHARED_Q2_4 */
	0xF,	/* SHARED_Q2_5 */
	0xF,	/* SHARED_Q2_6 */
	0xF,	/* SHARED_Q2_7 */
	0xF,	/* SHARED_Q2_8 */
	0xD,	/* SHARED_Q2_9 */
	0xD,	/* SHARED_Q2_10 */
	0xD,	/* SHARED_Q2_11 */
	0xD,	/* SHARED_Q2_12 */
	0xD,	/* SHARED_Q3_1 */
	0xD,	/* SHARED_Q3_2 */
	0xD,	/* SHARED_Q3_3 */
	0xD,	/* SHARED_Q3_4 */
	0xF,	/* SHARED_Q3_5 */
	0xF,	/* SHARED_Q3_6 */
	0xF,	/* SHARED_Q3_7 */
	0xF,	/* SHARED_Q3_8 */
	0xF,	/* SHARED_Q3_9 */
	0xF,	/* SHARED_Q3_10 */
	0xF,	/* SHARED_Q3_11 */
	0xF,	/* SHARED_Q3_12 */
	0xF,	/* SHARED_Q4_1 */
	0xF,	/* SHARED_Q4_2 */
	0xF,	/* SHARED_Q4_3 */
	0xF,	/* SHARED_Q4_4 */
	0xF,	/* SHARED_Q4_5 */
	0xF,	/* SHARED_Q4_6 */
	0xF,	/* SHARED_Q4_7 */
	0xF,	/* SHARED_Q4_8 */
	0xF,	/* SHARED_Q4_9 */
	0xF,	/* SHARED_Q4_10 */
	0xF,	/* SHARED_Q4_11 */
	0xF	/* SHARED_Q4_12 */
};

/* For dedicated IO */
unsigned long sys_mgr_init_table_dedicated[CONFIG_HPS_PINMUX_NUM_DEDICATED] = {
	0x0,	/* DEDICATED_PINMUX_1 */
	0x0,	/* DEDICATED_PINMUX_2 */
	0x0,	/* DEDICATED_PINMUX_3 */
	0x8,	/* DEDICATED_PINMUX_4 */
	0x8,	/* DEDICATED_PINMUX_5 */
	0x8,	/* DEDICATED_PINMUX_6 */
	0x8,	/* DEDICATED_PINMUX_7 */
	0x8,	/* DEDICATED_PINMUX_8 */
	0x8,	/* DEDICATED_PINMUX_9 */
	0x8,	/* DEDICATED_PINMUX_10 */
	0xF,	/* DEDICATED_PINMUX_11 */
	0xF,	/* DEDICATED_PINMUX_12 */
	0xF,	/* DEDICATED_PINMUX_13 */
	0xF,	/* DEDICATED_PINMUX_14 */
	0xF,	/* DEDICATED_PINMUX_15 */
	0xD,	/* DEDICATED_PINMUX_16 */
	0xD,	/* DEDICATED_PINMUX_17 */
};

/* For dedicated IO configuration */
unsigned long sys_mgr_init_table_dedicated_cfg
	[CONFIG_HPS_PINMUX_NUM_DEDICATED_CFG] = {
	0x0,		/* DEDICATED_IOBANK */
	0x51010,	/* DEDICATED_CONFIG_1 */
	0x51010,	/* DEDICATED_CONFIG_2 */
	0x51010,	/* DEDICATED_CONFIG_3 */
	0x40605,	/* DEDICATED_CONFIG_4 */
	0x40605,	/* DEDICATED_CONFIG_5 */
	0x00605,	/* DEDICATED_CONFIG_6 */
	0x40605,	/* DEDICATED_CONFIG_7 */
	0x40605,	/* DEDICATED_CONFIG_8 */
	0x40605,	/* DEDICATED_CONFIG_9 */
	0x10605,	/* DEDICATED_CONFIG_10 */
	0x51010,	/* DEDICATED_CONFIG_11 */
	0x51010,	/* DEDICATED_CONFIG_12 */
	0x51010,	/* DEDICATED_CONFIG_13 */
	0x51010,	/* DEDICATED_CONFIG_14 */
	0x51010,	/* DEDICATED_CONFIG_15 */
	0x03030,	/* DEDICATED_CONFIG_16 */
	0x23030,	/* DEDICATED_CONFIG_17 */
};

/* For peripheral controller use FPGA fabric */
unsigned long sys_mgr_init_table_fpga[CONFIG_HPS_PINMUX_NUM_FPGA] = {
	0,	/* EMAC0USEFPGA */
	0,	/* EMAC1USEFPGA */
	0,	/* EMAC2USEFPGA */
	0,	/* I2C0USEFPGA */
	0,	/* I21USEFPGA */
	0,	/* I2CEMAC0USEFPGA */
	0,	/* I2CEMAC1USEFPGA */
	0,	/* I2CEMAC2USEFPGA */
	0,	/* NANDUSEFPGA */
	0,	/* QSPIUSEFPGA */
	0,	/* SDMMCUSEFPGA */
	0,	/* SPIM0USEFPGA */
	0,	/* SPIM1USEFPGA */
	0,	/* SPIS0USEFPGA */
	0,	/* SPIS1USEFPGA */
	0,	/* UART0USEFPGA */
	0,	/* UART1USEFPGA */
};
