
/* This file is generated by Preloader Generator */

#ifndef _PRELOADER_PINMUX_CONFIG_H_
#define _PRELOADER_PINMUX_CONFIG_H_

/* Info easily for user to decode which peripherals are muxed out */
#define CONFIG_HPS_EMAC0	(0)
#define CONFIG_HPS_EMAC1	(0)
#define CONFIG_HPS_EMAC2	(0)
#define CONFIG_HPS_USB0		(1)
#define CONFIG_HPS_USB1		(0)
#define CONFIG_HPS_NAND		(0)
#define CONFIG_HPS_SDMMC	(1)
#define CONFIG_HPS_QSPI		(1)
#define CONFIG_HPS_UART0	(1)
#define CONFIG_HPS_UART1	(1)
#define CONFIG_HPS_TRACE	(0)
#define CONFIG_HPS_I2C0		(0)
#define CONFIG_HPS_I2C1		(0)
#define CONFIG_HPS_I2CEMAC0	(0)
#define CONFIG_HPS_I2CEMAC1	(0)
#define CONFIG_HPS_I2CEMAC2	(0)
#define CONFIG_HPS_SPIM0	(0)
#define CONFIG_HPS_SPIM1	(0)
#define CONFIG_HPS_SPIS0	(0)
#define CONFIG_HPS_SPIS1	(0)
#define CONFIG_HPS_MDIO0	(0)
#define CONFIG_HPS_MDIO1	(0)
#define CONFIG_HPS_MDIO2	(0)

#define CONFIG_HPS_SDMMC_BUSWIDTH (4)
#define CONFIG_HPS_NAND_BUSWIDTH  (8)
#define CONFIG_HPS_TRACE_BUSWIDTH (4)

#define CONFIG_HPS_QSPI_CS3	(0)
#define CONFIG_HPS_QSPI_CS2	(0)
#define CONFIG_HPS_QSPI_CS1	(0)
#define CONFIG_HPS_QSPI_CS0	(1)
#define CONFIG_HPS_QSPI_DATA	(4)

#define CONFIG_HPS_UART0_TX	(0)
#define CONFIG_HPS_UART0_CTS	(0)
#define CONFIG_HPS_UART0_RTS	(0)
#define CONFIG_HPS_UART0_RX	(0)

#define CONFIG_HPS_UART1_TX	(1)
#define CONFIG_HPS_UART1_CTS	(0)
#define CONFIG_HPS_UART1_RTS	(0)
#define CONFIG_HPS_UART1_RX	(1)

#define CONFIG_HPS_SPIM0_SS0	(0)
#define CONFIG_HPS_SPIM0_SS1	(0)
#define CONFIG_HPS_SPIM1_SS0	(0)
#define CONFIG_HPS_SPIM1_SS1	(0)

/* Pin MUX data */
/* For shared IO 48 */
#define CONFIG_HPS_PINMUX_NUM_SHARED	(48)

/* For dedicated IO */
#define CONFIG_HPS_PINMUX_NUM_DEDICATED (17)

/* For dedicated IO configuration */
#define CONFIG_HPS_PINMUX_NUM_DEDICATED_CFG (18)

/* For peripheral controller use FPGA fabric */
#define CONFIG_HPS_PINMUX_NUM_FPGA	(17)

#endif /* _PRELOADER_PINMUX_CONFIG_H_ */
