#ifndef __SDRAM_CONFIG_H
#define __SDRAM_CONFIG_H

/*
 * Firewall setup for DDR
 * This applicable for master when its not in secure state (as secure master
 * can access to entiree DDR). For non secure master, you would need to
 * specify the memory region that can be accessed.
 *
 * ENABLE - 1 for enable while 0 for disable
 * START & END - valid value 0 to 0xFFFF
 *		Example: if start=0, end=0, enable=1, the first 64kB region
 *		can be accessed by non secure master (either MPU, L3 or FPGA)
 */
#define CONFIG_HPS_SDR_MPU0_ENABLE	(1)
#define CONFIG_HPS_SDR_MPU0_START	(0)
#define CONFIG_HPS_SDR_MPU0_END		(0xFFFF)

#define CONFIG_HPS_SDR_MPU1_ENABLE	(0)
#define CONFIG_HPS_SDR_MPU1_START	(0)
#define CONFIG_HPS_SDR_MPU1_END		(0)

#define CONFIG_HPS_SDR_MPU2_ENABLE	(0)
#define CONFIG_HPS_SDR_MPU2_START	(0)
#define CONFIG_HPS_SDR_MPU2_END		(0)

#define CONFIG_HPS_SDR_MPU3_ENABLE	(0)
#define CONFIG_HPS_SDR_MPU3_START	(0)
#define CONFIG_HPS_SDR_MPU3_END		(0)

#define CONFIG_HPS_SDR_HPS_L3_0_ENABLE	(1)
#define CONFIG_HPS_SDR_HPS_L3_0_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_0_END	(0xFFFF)

#define CONFIG_HPS_SDR_HPS_L3_1_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_1_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_1_END	(0)

#define CONFIG_HPS_SDR_HPS_L3_2_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_2_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_2_END	(0)

#define CONFIG_HPS_SDR_HPS_L3_3_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_3_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_3_END	(0)

#define CONFIG_HPS_SDR_HPS_L3_4_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_4_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_4_END	(0)

#define CONFIG_HPS_SDR_HPS_L3_5_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_5_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_5_END	(0)

#define CONFIG_HPS_SDR_HPS_L3_6_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_6_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_6_END	(0)

#define CONFIG_HPS_SDR_HPS_L3_7_ENABLE	(0)
#define CONFIG_HPS_SDR_HPS_L3_7_START	(0)
#define CONFIG_HPS_SDR_HPS_L3_7_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM0_0_ENABLE	(1)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_0_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_0_END	(0xFFFF)

#define CONFIG_HPS_SDR_FPGA2SDRAM0_1_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_1_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_1_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM0_2_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_2_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_2_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM0_3_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_3_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM0_3_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM1_0_ENABLE	(1)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_0_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_0_END	(0xFFFF)

#define CONFIG_HPS_SDR_FPGA2SDRAM1_1_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_1_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_1_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM1_2_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_2_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_2_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM1_3_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_3_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM1_3_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM2_0_ENABLE	(1)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_0_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_0_END	(0xFFFF)

#define CONFIG_HPS_SDR_FPGA2SDRAM2_1_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_1_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_1_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM2_2_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_2_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_2_END	(0)

#define CONFIG_HPS_SDR_FPGA2SDRAM2_3_ENABLE	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_3_START	(0)
#define CONFIG_HPS_SDR_FPGA2SDRAM2_3_END	(0)

#endif	/*#ifndef__SDRAM_CONFIG_H*/
