//
// This header file has been generated by pllconvert.py
//

#ifndef _PLLDATA_H_
#define _PLLDATA_H_

#include <common.h>

typedef struct
{
    char cmd;
    u32 addr;
    u8 value;
} PLLStructItem_t;

extern PLLStructItem_t PLLStructItemList[];
extern u32 PLLStructItems;
extern char PLLFilename[];

#endif /* _PLLDATA_H_ */

