#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (C) 2014 Altera Corporation <www.altera.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= cff.o sdram.o clock_manager.o ecc_ram.o fpga_manager.o gic.o
obj-y	+= interrupts.o lowlevel_init.o misc.o nic301.o pl310.o
obj-y	+= reset_manager.o sdram.o s_init.o
